--DIA 27/08/2026

--LETS GO TREINO 15:30 ATÉ 15:39



ALTER TABLE T_UNV_ALUNO
 ADD SITUACAO CHAR(1);
 
ALTER TABLE T_UNV_PROFESSOR 
 ADD SITUACAO CHAR(1);

ALTER TABLE T_UNV_DISCIPLINA
 RENAME COLUMN CARGA_HORARIA TO CH;
 
RENAME T_UNV_ALUNO TO DISCENTE;

RENAME T_UNV_PROFESSOR TO DOCENTE;

ALTER TABLE T_UNV_DISCIPLINA
 MODIFY EMENTA LONG VARCHAR;

